export default {
  index: 'Choose your stack',
  'incident-loop': 'Incident loop (start here)',
  mcp: 'MCP server',
  react: 'React',
  web: 'Vanilla JS',
  vue: 'Vue 3',
  svelte: 'Svelte',
  angular: 'Angular',
  'react-native': 'React Native',
  ios: 'iOS (Swift)',
  android: 'Android (Kotlin)',
  flutter: 'Flutter',
  capacitor: 'Capacitor',
  mobile: { title: 'Mobile (overview)', display: 'hidden' },
}
