import { Octokit } from '@octokit/rest'
import type { FixContext, FixResult } from './types.js'

export interface PRCreateOptions {
  githubToken: string
  owner: string
  repo: string
  baseBranch?: string
}

export function buildPRBody(context: FixContext, fixResult: FixResult): string {
  const reproSteps = context.reproductionSteps.length > 0
    ? context.reproductionSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')
    : 'No reproduction steps available'

  const sentry = context.sentryAnalysis
    ? `\n### Sentry Correlation\n- Issue: ${context.sentryAnalysis.issueUrl ?? 'N/A'}\n- Root Cause: ${context.sentryAnalysis.rootCause ?? 'N/A'}`
    : ''

  return `## Mushi Mushi Auto-Fix

**Report**: \`${context.reportId}\`
**Category**: ${context.report.category} | **Severity**: ${context.report.severity}

### Summary
${context.report.summary ?? context.report.description.slice(0, 200)}

### Root Cause
${context.report.rootCause ?? 'Determined from automated analysis'}

### Reproduction Steps
${reproSteps}

### Fix Rationale
${fixResult.summary}

### Changes
- Files: ${fixResult.filesChanged.join(', ')}
- Lines changed: ${fixResult.linesChanged}
${sentry}

---
*This PR was generated by Mushi Mushi. Review carefully before merging.*`
}

export async function createPR(
  options: PRCreateOptions,
  context: FixContext,
  fixResult: FixResult,
): Promise<string> {
  const octokit = new Octokit({ auth: options.githubToken })

  const title = `fix(${context.report.component ?? 'app'}): ${context.report.summary?.slice(0, 72) ?? 'Auto-fix from Mushi report'}`
  const body = buildPRBody(context, fixResult)

  const { data: pr } = await octokit.pulls.create({
    owner: options.owner,
    repo: options.repo,
    title,
    body,
    head: fixResult.branch,
    base: options.baseBranch ?? 'main',
  })

  // Add labels
  const labels = ['mushi-autofix']
  if (context.report.severity) labels.push(`severity:${context.report.severity}`)

  await octokit.issues.addLabels({
    owner: options.owner,
    repo: options.repo,
    issue_number: pr.number,
    labels,
  }).catch(() => {})

  return pr.html_url
}
