import { describe, it, expect } from 'vitest'
import { buildPRBody } from './github.js'
import type { FixContext, FixResult } from './types.js'

describe('buildPRBody', () => {
  const context: FixContext = {
    reportId: 'rpt_abc',
    report: {
      summary: 'Modal closes unexpectedly',
      category: 'bug',
      severity: 'high',
      component: 'Modal',
      rootCause: 'Focus trap breaks on escape',
      description: 'The modal closes when pressing escape even with unsaved changes',
    },
    reproductionSteps: ['Open modal', 'Type text', 'Press Escape'],
  } as FixContext

  const fixResult: FixResult = {
    branch: 'fix/modal-escape',
    filesChanged: ['src/Modal.tsx', 'src/Modal.test.tsx'],
    linesChanged: 15,
    success: true,
    summary: 'Added dirty-state guard to escape handler',
  }

  it('includes report metadata', () => {
    const body = buildPRBody(context, fixResult)
    expect(body).toContain('rpt_abc')
    expect(body).toContain('bug')
    expect(body).toContain('high')
  })

  it('includes summary from report', () => {
    const body = buildPRBody(context, fixResult)
    expect(body).toContain('Modal closes unexpectedly')
  })

  it('includes reproduction steps', () => {
    const body = buildPRBody(context, fixResult)
    expect(body).toContain('1. Open modal')
    expect(body).toContain('2. Type text')
  })

  it('includes fix details', () => {
    const body = buildPRBody(context, fixResult)
    expect(body).toContain('Added dirty-state guard')
    expect(body).toContain('src/Modal.tsx')
    expect(body).toContain('15')
  })

  it('shows "No reproduction steps" when empty', () => {
    const ctxNoSteps = { ...context, reproductionSteps: [] }
    const body = buildPRBody(ctxNoSteps, fixResult)
    expect(body).toContain('No reproduction steps')
  })

  it('includes Sentry section when available', () => {
    const ctxSentry = {
      ...context,
      sentryAnalysis: { issueUrl: 'https://sentry.io/123', rootCause: 'NPE' },
    } as FixContext
    const body = buildPRBody(ctxSentry, fixResult)
    expect(body).toContain('Sentry')
    expect(body).toContain('https://sentry.io/123')
  })

  it('includes auto-fix footer', () => {
    const body = buildPRBody(context, fixResult)
    expect(body).toContain('generated by Mushi Mushi')
  })
})
