-- =============================================================================
-- §4: prompt-auto-tune support columns.
--
-- Adds the metadata needed by the new `prompt-auto-tune` Edge Function:
--   - classification_evaluations.disagreement_reason: short tag (e.g.
--     'wrong_severity', 'missing_component', 'overconfident') the judge
--     emits when classification_agreed = false. Lets us bucket failures
--     when generating a candidate prompt instead of stuffing the entire
--     `judge_reasoning` blob into the LLM context window.
--   - prompt_versions.auto_generated: true when prompt-auto-tune created
--     the row. Distinguishes operator-authored experiments from machine
--     proposals so the Prompt Lab can badge them and never auto-promote
--     without human review.
--   - prompt_versions.auto_generation_metadata: jsonb {
--       parentVersion, failureCount, topBuckets, generatedAt, model
--     }. Used by the Prompt Lab diff UI to surface "why this candidate
--     was generated".
--   - prompt_versions.parent_version_id: the prompt this one forked from.
--     Lets the diff UI compare candidate ↔ parent without re-querying
--     active state at click time.
-- =============================================================================

ALTER TABLE classification_evaluations
  ADD COLUMN IF NOT EXISTS disagreement_reason TEXT;

COMMENT ON COLUMN classification_evaluations.disagreement_reason IS
  'Short failure-mode tag the judge emits when classification_agreed = false (e.g. wrong_severity, missing_component). NULL when agreed.';

CREATE INDEX IF NOT EXISTS idx_class_evals_disagreement
  ON classification_evaluations (project_id, disagreement_reason)
  WHERE disagreement_reason IS NOT NULL;

ALTER TABLE prompt_versions
  ADD COLUMN IF NOT EXISTS auto_generated            BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_generation_metadata  JSONB,
  ADD COLUMN IF NOT EXISTS parent_version_id         UUID REFERENCES prompt_versions(id) ON DELETE SET NULL;

COMMENT ON COLUMN prompt_versions.auto_generated IS
  'True when generated by the prompt-auto-tune Edge Function. Auto candidates require human approval to promote.';
COMMENT ON COLUMN prompt_versions.auto_generation_metadata IS
  'Audit trail for auto-generated prompts: { parentVersion, failureCount, topBuckets, generatedAt, model }.';
COMMENT ON COLUMN prompt_versions.parent_version_id IS
  'The prompt this row was forked from. Set by prompt-auto-tune; null for hand-authored prompts.';

CREATE INDEX IF NOT EXISTS idx_prompt_versions_auto_pending
  ON prompt_versions (project_id, stage, created_at DESC)
  WHERE auto_generated = true AND is_active = false;

-- =========================================================================
-- Schedule the weekly auto-tune cron. Runs every Sunday at 07:00 UTC,
-- one hour after the library-modernizer (06:00) so they don't overlap.
-- Guarded so the migration replays cleanly if pg_cron isn't installed.
-- =========================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    RAISE NOTICE 'pg_cron not installed — skipping prompt-auto-tune schedule';
    RETURN;
  END IF;

  PERFORM cron.unschedule('mushi-prompt-auto-tune-weekly')
  WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'mushi-prompt-auto-tune-weekly');

  PERFORM cron.schedule(
    'mushi-prompt-auto-tune-weekly',
    '0 7 * * 0',
    $cron$
      SELECT net.http_post(
        url := current_setting('app.settings.supabase_url', true) || '/functions/v1/prompt-auto-tune',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || current_setting('app.settings.service_role_key', true)
        ),
        body := jsonb_build_object('trigger', 'cron')
      );
    $cron$
  );
END
$$;
