-- Add friendly title and product-area tag to reports
-- title: human-readable headline generated by Stage 2 LLM (non-engineer friendly)
-- area_tag: coarse product-area label (e.g. "Checkout", "Onboarding") from Stage 2
alter table reports
  add column if not exists title text,
  add column if not exists area_tag text;

comment on column reports.title is
  'Friendly, plain-language headline generated by Stage 2 classifier — suitable for non-engineers. Null for reports classified before this column was added; UI falls back to summary.';
comment on column reports.area_tag is
  'Coarse product-area label (e.g. "Checkout", "Auth", "Onboarding") produced by Stage 2. Used for tag chips and filtering.';
