/**
 * KENSAURUS spine — app catalog (schema v2, updated 2026-10-08).
 *
 * GENERATED by scripts/spine-sync.mjs from well-known/kensaurus-apps.json in
 * kensaurus/yen-yen. Do not edit — change the manifest and re-run the sync.
 * Vendored copies are checked against spine.lock.json by check-spine.mjs.
 */

export type KensaurusPlatform = 'android' | 'ios' | 'physical' | 'sdk' | 'web'
export type KensaurusPricing = 'free' | 'freemium' | 'open-source' | 'paid'

export interface KensaurusDeepLinks {
  /** Custom URL scheme the native app registers (no `://`). */
  readonly scheme?: string
  /** Universal / App Link base — the app's own web URL. */
  readonly universal?: string
}

export interface KensaurusApp {
  /** Canonical app id: the one id used for events, wallet, quota and URLs. */
  readonly id: string
  /** Full store name, "brand – what it does": list titles and headings. */
  readonly name: string
  /** The brand alone, derived from `name`: for sentences ("Get your {brand} stamp"). */
  readonly brand: string
  /** Short ids still emitted by shipped builds; normalised server-side. */
  readonly aliases: readonly string[]
  /** App-specific event that marks activation (a passport stamp). */
  readonly activationEvent?: string
  readonly deepLinks?: KensaurusDeepLinks
  readonly tagline: Readonly<Record<string, string>>
  readonly blurb?: Readonly<Record<string, string>>
  readonly web: string
  readonly icon: string
  readonly ios?: string
  readonly iosAppId?: string
  readonly android?: string
  readonly androidPackage?: string
  readonly platforms: readonly KensaurusPlatform[]
  readonly pricing?: KensaurusPricing
  readonly role?: 'hub'
  readonly facebook?: string
  readonly github?: string
  readonly googleMaps?: string
  readonly instagram?: string
  readonly npm?: string
}

export interface KensaurusManifest {
  readonly version: number
  readonly updated: string
  readonly brand: {
    readonly name: string
    readonly site: string
    readonly github: string
  }
  readonly apps: readonly KensaurusApp[]
}

export const KENSAURUS_MANIFEST = {
  version: 2,
  updated: '2026-10-08',
  brand: {
    name: 'KENSAURUS',
    site: 'https://kensaur.us',
    github: 'https://github.com/kensaurus',
  },
  apps: [
    {
      id: 'glot-it',
      name: 'glot.it – Learn Thai',
      brand: 'glot.it',
      aliases: ['glot'],
      activationEvent: 'lesson_completed',
      deepLinks: {
        scheme: 'com.glotit.app',
        universal: 'https://kensaur.us/glot-it/',
      },
      tagline: {
        en: 'Bite-size lessons + AI tutor',
      },
      web: 'https://kensaur.us/glot-it/',
      icon: 'https://kensaur.us/glot-it/icon-512.png',
      ios: 'https://apps.apple.com/app/glot-it/id6761582648',
      iosAppId: '6761582648',
      android: 'https://play.google.com/store/apps/details?id=com.glotit.app',
      androidPackage: 'com.glotit.app',
      platforms: ['ios', 'android', 'web'],
      pricing: 'freemium',
    },
    {
      id: 'yen-yen',
      name: 'yen-yen – Expense Tracker',
      brand: 'yen-yen',
      aliases: [],
      activationEvent: 'first_expense_saved',
      deepLinks: {
        scheme: 'yenyen',
        universal: 'https://kensaur.us/yen-yen/',
      },
      tagline: {
        en: 'Where did the money go?',
      },
      blurb: {
        en: 'Household kakeibo. Paste a statement. See the week.',
      },
      web: 'https://kensaur.us/yen-yen/',
      icon: 'https://kensaur.us/yen-yen/icon.svg',
      ios: 'https://apps.apple.com/app/id6764548441',
      iosAppId: '6764548441',
      android: 'https://play.google.com/store/apps/details?id=app.yenyen',
      androidPackage: 'app.yenyen',
      platforms: ['ios', 'android', 'web'],
      pricing: 'freemium',
    },
    {
      id: 'the-wanting-mind',
      name: 'the wanting mind – Living Book',
      brand: 'the wanting mind',
      aliases: ['twm'],
      activationEvent: 'chapter_finished',
      deepLinks: {
        scheme: 'us.kensaur.thewantingmind',
        universal: 'https://kensaur.us/the-wanting-mind/',
      },
      tagline: {
        en: 'Why we want. Read, hear, ask.',
      },
      blurb: {
        en: 'Interactive webbook. 268 concepts, 242 citations.',
      },
      web: 'https://kensaur.us/the-wanting-mind/',
      icon: 'https://kensaur.us/the-wanting-mind/pwa-512x512.png',
      ios: 'https://apps.apple.com/app/the-wanting-mind/id6761361305',
      iosAppId: '6761361305',
      android: 'https://play.google.com/store/apps/details?id=us.kensaur.thewantingmind',
      androidPackage: 'us.kensaur.thewantingmind',
      platforms: ['ios', 'android', 'web'],
      pricing: 'freemium',
    },
    {
      id: 'help-her-take-photo',
      name: 'help her take photo – Pose Cam',
      brand: 'help her take photo',
      aliases: ['hhtp'],
      activationEvent: 'first_keeper',
      deepLinks: {
        scheme: 'helphertakephoto',
        universal: 'https://kensaur.us/help-her-take-photo/',
      },
      tagline: {
        en: 'Direct her pose, nail the shot',
      },
      web: 'https://kensaur.us/help-her-take-photo/',
      icon: 'https://kensaur.us/help-her-take-photo/assets/apple-touch-icon.png',
      ios: 'https://apps.apple.com/app/id6762513666',
      iosAppId: '6762513666',
      android: 'https://play.google.com/store/apps/details?id=com.kensaurus.helphertakephoto',
      androidPackage: 'com.kensaurus.helphertakephoto',
      platforms: ['ios', 'android', 'web'],
      pricing: 'free',
    },
    {
      id: 'how-to-talk-to-girls',
      name: 'lets-talk – Conversation Coach',
      brand: 'lets-talk',
      aliases: ['htttg'],
      activationEvent: 'activated',
      deepLinks: {
        scheme: 'us.kensaur.howtotalktogirls',
        universal: 'https://talk.kensaur.us',
      },
      tagline: {
        en: 'Practice the hard talk first',
      },
      web: 'https://talk.kensaur.us',
      github: 'https://github.com/kensaurus/cooler-heads',
      icon: 'https://talk.kensaur.us/pwa-192.png',
      iosAppId: '6799392790',
      android: 'https://play.google.com/store/apps/details?id=us.kensaur.howtotalktogirls',
      androidPackage: 'us.kensaur.howtotalktogirls',
      platforms: ['android', 'web'],
      pricing: 'free',
    },
    {
      id: 'solo-boss',
      name: '一人社長 Solo Boss',
      brand: '一人社長 Solo Boss',
      aliases: [],
      tagline: {
        ja: '帳簿はいまの会計ソフトのまま。決算書・別表・e-Taxの送信ファイルまで。',
        en: 'Year-end statements and e-Tax filing files for one-person companies in Japan. AI drafts; you confirm.',
      },
      web: 'https://solo-boss.kensaur.us/',
      icon: 'https://solo-boss.kensaur.us/apple-touch-icon.png',
      platforms: ['web'],
      pricing: 'free',
    },
    {
      id: 'tsumagoi',
      name: 'Tsumagoi Work&Camp 嬬恋牧場',
      brand: 'Tsumagoi Work&Camp 嬬恋牧場',
      aliases: [],
      tagline: {
        ja: '標高1,444mのワーケーションキャンプ場。光ファイバー、焚き火、満天の星。',
        en: 'Physical coworking camp and digital-nomad base at 1,444 m in Gunma, Japan — fiber internet, campfires, starlit skies near Kusatsu Onsen.',
      },
      web: 'https://tsumagoi.kensaur.us/',
      icon: 'https://tsumagoi.kensaur.us/apple-touch-icon.png',
      instagram: 'https://www.instagram.com/tsumagoicamp/',
      facebook: 'https://www.facebook.com/profile.php?id=61592113053042',
      googleMaps: 'https://maps.app.goo.gl/JCNnTfsdQVHCS1FA7',
      platforms: ['web', 'physical'],
      pricing: 'paid',
    },
    {
      id: 'mushi-mushi',
      name: 'mushi-mushi',
      brand: 'mushi-mushi',
      aliases: ['mushi'],
      tagline: {
        en: 'Open-source in-app bug reporting — screenshots, console, and network context in every report.',
      },
      web: 'https://kensaur.us/mushi-mushi/',
      github: 'https://github.com/kensaurus/mushi-mushi',
      npm: 'https://www.npmjs.com/package/@mushi-mushi/core',
      icon: 'https://kensaur.us/mushi-mushi/admin/favicon.svg',
      platforms: ['web', 'sdk'],
      pricing: 'open-source',
    },
    {
      id: 'cursor-kenji',
      name: 'kenji skills',
      brand: 'kenji skills',
      aliases: [],
      tagline: {
        en: 'Agent skills, slash commands, and subagents for Claude Code, Cursor, Codex, and Gemini. You say the job; the playbook runs.',
      },
      web: 'https://github.com/kensaurus/skills',
      github: 'https://github.com/kensaurus/skills',
      npm: 'https://www.npmjs.com/package/@kensaurus/skills',
      icon: 'https://github.com/kensaurus.png',
      platforms: ['sdk'],
      pricing: 'open-source',
    },
    {
      id: 'portfolio',
      name: 'KENSAURUS',
      brand: 'KENSAURUS',
      aliases: ['kensaurus-hub'],
      tagline: {
        en: 'Everything else built under the same roof.',
      },
      web: 'https://kensaur.us/?view=portfolio',
      icon: 'https://kensaur.us/favicon.svg',
      role: 'hub',
      platforms: ['web'],
    },
  ],
} as const satisfies KensaurusManifest

export const KENSAURUS_APPS = KENSAURUS_MANIFEST.apps

/** Every canonical app id, in manifest order. */
export const KENSAURUS_APP_IDS = ['glot-it', 'yen-yen', 'the-wanting-mind', 'help-her-take-photo', 'how-to-talk-to-girls', 'solo-boss', 'tsumagoi', 'mushi-mushi', 'cursor-kenji', 'portfolio'] as const

export type KensaurusAppId = (typeof KENSAURUS_APP_IDS)[number]

/** alias → canonical id. Only aliases; canonical ids are not keys here. */
export const KENSAURUS_APP_ALIASES: Readonly<Record<string, KensaurusAppId>> = {
  glot: 'glot-it',
  twm: 'the-wanting-mind',
  hhtp: 'help-her-take-photo',
  htttg: 'how-to-talk-to-girls',
  mushi: 'mushi-mushi',
  'kensaurus-hub': 'portfolio',
}
