/**
 * FILE: analytics-taxonomy.generated.ts
 * GENERATED by scripts/gen-analytics-taxonomy.mjs from
 * packages/core/src/analytics-taxonomy.ts — DO NOT EDIT BY HAND.
 * Run `node scripts/gen-analytics-taxonomy.mjs` after changing the source.
 */

export const EVENT_NAME_RE = /^[a-z][a-z0-9_]{1,63}$/
export const PII_PROPERTY_KEY_RE = /(email|phone|password|passwd|token|secret|ssn|address|credit|card|iban)/i
export const RESERVED_PROPERTY_PREFIX = '$'

export const EVENT_PROPERTY_LIMITS = {
  "maxKeys": 40,
  "maxKeyLength": 64,
  "maxValueLength": 256,
  "maxBytes": 8192,
  "maxClientBatch": 20,
  "maxServerBatch": 50,
  "maxEventNamesPerProject": 200
} as const

export const MUSHI_SURFACES = ["web","console","docs","cli","mcp","server","mobile"] as const
export type MushiSurface = (typeof MUSHI_SURFACES)[number]

export const MUSHI_EVENTS = {
  "page_view": {
    "surface": [
      "web",
      "docs",
      "console"
    ],
    "required": []
  },
  "docs_page_view": {
    "surface": "docs",
    "required": [
      "route"
    ]
  },
  "landing_view": {
    "surface": "docs",
    "required": []
  },
  "cta_click": {
    "surface": "docs",
    "required": [
      "cta_id",
      "location"
    ]
  },
  "quickstart_view": {
    "surface": "docs",
    "required": []
  },
  "pricing_view": {
    "surface": "docs",
    "required": []
  },
  "connect_demo_click": {
    "surface": "docs",
    "required": [
      "href"
    ]
  },
  "signup_click": {
    "surface": "docs",
    "required": [
      "href"
    ]
  },
  "signup_completed": {
    "surface": "console",
    "required": [
      "signup_source"
    ]
  },
  "report_opened": {
    "surface": [
      "console",
      "mcp"
    ],
    "required": [
      "report_id"
    ]
  },
  "fix_context_pulled": {
    "surface": [
      "console",
      "mcp"
    ],
    "required": [
      "report_id"
    ]
  },
  "fix_dispatched": {
    "surface": [
      "console",
      "mcp"
    ],
    "required": [
      "report_id",
      "agent"
    ]
  },
  "invite_sent": {
    "surface": "console",
    "required": []
  },
  "upgrade_clicked": {
    "surface": "console",
    "required": [
      "plan"
    ]
  },
  "test_report_sent": {
    "surface": "console",
    "required": [
      "project_id"
    ]
  },
  "project_created": {
    "surface": "server",
    "required": [
      "project_id"
    ]
  },
  "key_minted": {
    "surface": "server",
    "required": [
      "project_id"
    ]
  },
  "first_report_received": {
    "surface": "server",
    "required": [
      "project_id"
    ]
  },
  "fix_merged": {
    "surface": "server",
    "required": [
      "project_id"
    ]
  },
  "upgrade_completed": {
    "surface": "server",
    "required": [
      "project_id",
      "plan"
    ]
  },
  "loop_impression": {
    "surface": "web",
    "required": []
  },
  "loop_click": {
    "surface": "web",
    "required": []
  },
  "loop_signup": {
    "surface": "console",
    "required": [
      "ref"
    ]
  }
} as const

export type MushiEventName = keyof typeof MUSHI_EVENTS
export const MUSHI_EVENT_NAMES = Object.keys(MUSHI_EVENTS) as MushiEventName[]
export const ACTIVATION_EVENT: MushiEventName = 'first_report_received'

export function isValidEventName(name: unknown): name is string {
  return typeof name === 'string' && EVENT_NAME_RE.test(name)
}
