/**
 * FILE: console-routes.generated.ts
 * PURPOSE: Canonical admin-console route directory for NL assistant nav validation.
 * GENERATED BY: scripts/build-console-knowledge.mjs — do not edit by hand.
 */

export interface ConsoleRouteEntry {
  path: string
  label: string
  description: string
  group: string
  keywords: string[]
}

export const CONSOLE_ROUTES: ConsoleRouteEntry[] = [
  { path: "/onboarding", label: "Get started", description: "Three-step setup: create a project, install the widget, send a test bug.", group: "Start", keywords: ["setup","install","quickstart","first run","widget","snippet","project"] },
  { path: "/connect", label: "Connect & Update", description: "Wire up your editor and app: SDK install, MCP for Cursor/Claude, upgrade PRs.", group: "Start", keywords: ["install","sdk","upgrade","update","mcp","cursor","npm","package","editor"] },
  { path: "/overview", label: "Overview", description: "Portfolio view — all connected projects at a glance with activity and open tickets.", group: "Start", keywords: ["overview","portfolio","all projects","health","consolidated"] },
  { path: "/dashboard", label: "Dashboard", description: "Live PDCA loop — bugs in, fixes out, judge scores, shipped impact.", group: "Start", keywords: ["home","overview","kpi","metrics","loop","landing","summary"] },
  { path: "/inbox", label: "Action Inbox", description: "Action inbox — every event awaiting your decision in one place.", group: "Start", keywords: ["inbox","action","todo","pending","decision","next"] },
  { path: "/feedback", label: "Support", description: "Feedback you submitted to Mushi.", group: "Start", keywords: ["feedback","feature","bug","request","support"] },
  { path: "/feature-board", label: "Feature board", description: "Community feature requests and votes.", group: "Start", keywords: ["features","roadmap","votes","board"] },
  { path: "/reports", label: "Reports", description: "Triage inbound bug reports — grouped, scored, ranked.", group: "Plan", keywords: ["bugs","triage","complaints","issues","incidents","tickets"] },
  { path: "/content", label: "Content QA", description: "Review AI-generated and user-submitted content quality.", group: "Plan", keywords: ["content","qa","quality","moderation"] },
  { path: "/inventory", label: "User stories", description: "User-story inventory and live crawl proposals.", group: "Plan", keywords: ["stories","inventory","discovery","crawl"] },
  { path: "/graph", label: "Graph", description: "Fingerprint graph — dedup clusters and shared root causes.", group: "Plan", keywords: ["cluster","dedup","fingerprint","similar bugs","network","visualisation","reactflow"] },
  { path: "/explore", label: "Explore", description: "Map, chat with, and tour your indexed repository.", group: "Plan", keywords: ["codebase","atlas","understand","architecture","ask","tour","domains","codebase map"] },
  { path: "/queue", label: "Failed events", description: "Dead-letter queue for ingestion retries and poisoned events.", group: "Plan", keywords: ["dlq","dead letter","retry","failures","pipeline","failed events"] },
  { path: "/anti-gaming", label: "Anti-Gaming", description: "Spam, collusion, and duplicate-submission defences.", group: "Plan", keywords: ["spam","abuse","collusion","rate limit","fraud","dupes"] },
  { path: "/fixes", label: "Fixes", description: "Drafted pull requests from the auto-fix agent, ready to merge.", group: "Do", keywords: ["pull request","pr","patch","diff","merge","codex","llm","agent","drafts"] },
  { path: "/repo", label: "Repo", description: "Every auto-fix branch and PR across the connected GitHub repo, with CI status.", group: "Do", keywords: ["repo","repository","branch","branches","git","github","pr","pull request","ci","checks","merge","activity"] },
  { path: "/voice", label: "Voice", description: "Talk a bug or a fix request from your phone; confirm the transcript; the draft PR comes back as a push.", group: "Do", keywords: ["voice","mic","microphone","record","dictate","phone","audio","telegram","push","notify","pwa"] },
  { path: "/prompt-lab", label: "Prompt Lab", description: "Tune the prompts that turn reports into pull requests.", group: "Do", keywords: ["prompt","llm","model","ai","tuning","evals","template","system prompt"] },
  { path: "/judge", label: "Judge", description: "Independent quality grading for the auto-fix output.", group: "Check", keywords: ["score","eval","quality","grade","verification","llm-as-judge"] },
  { path: "/qa-coverage", label: "QA Coverage", description: "Scheduled Playwright user-story tests.", group: "Check", keywords: ["qa","playwright","stories","coverage","test"] },
  { path: "/fullstack-audit", label: "Full-Stack Audit", description: "End-to-end audit across frontend, API, and database.", group: "Check", keywords: ["audit","fullstack","fe","be","schema"] },
  { path: "/lessons", label: "Lessons", description: "Patterns learned from past bugs and fixes.", group: "Check", keywords: ["lessons","learned","patterns"] },
  { path: "/activity", label: "Activity", description: "Per-project activity — sessions, page views, identified vs. anonymous users, top routes.", group: "Check", keywords: ["sessions","users","page views","analytics","dau","activity","engagement"] },
  { path: "/analytics", label: "Users & Funnels", description: "Product analytics from Mushi.track() — event volume, funnels, next-step paths, people, and weekly retention.", group: "Check", keywords: ["funnel","funnels","events","track","analytics","retention","paths","people","conversion","cohort"] },
  { path: "/growth", label: "Growth", description: "Operator-only company funnel — activated external projects per week, by signup source.", group: "Check", keywords: ["growth","funnel","signups","activation","activated","paid","source","operator"] },
  { path: "/health", label: "Health", description: "System health — uptime, error rates, queue depth, backpressure.", group: "Check", keywords: ["status","uptime","availability","sentry","slo","monitoring","incidents","verification hub"] },
  { path: "/code-health", label: "Code Health", description: "Bundle-size trends and god-file LOC findings pushed from host-repo CI.", group: "Check", keywords: ["bundle","loc","god file","refactor","gzip","code health","ci","budget","file size"] },
  { path: "/recipe", label: "Recipe", description: "What this app is made of — schema, design system, routes, gates, CI, deploy, env and integrations — and where each drifted.", group: "Check", keywords: ["recipe","app recipe","schema","design system","tokens","gates","ci","deploy","env","integrations","drift","manifest","mushi.recipe.json"] },
  { path: "/portfolio", label: "Portfolio", description: "Every app in the team at once: worst recipe state, hole checks, SDK versions, and problems to fix once across apps.", group: "Check", keywords: ["portfolio","all apps","fix once","sdk skew","radar","holes","team","organization"] },
  { path: "/design", label: "Design system", description: "Design tokens, contrast pairs, type scale and the deviance score for off-token code; token and rule edits open a draft PR.", group: "Check", keywords: ["design","design system","tokens","dtcg","colors","contrast","typography","spacing","radius","deviance","off-token","rules"] },
  { path: "/drift", label: "Drift", description: "Schema and backend drift detection.", group: "Check", keywords: ["drift","schema","backend","migration"] },
  { path: "/anomalies", label: "Anomalies", description: "Statistical anomaly detection on metrics.", group: "Check", keywords: ["anomalies","spike","outlier","metrics"] },
  { path: "/releases", label: "Releases", description: "Shipped releases with reporter credit.", group: "Check", keywords: ["releases","changelog","ship","deploy"] },
  { path: "/intelligence", label: "Intelligence", description: "Cross-project insights: what fails most, who is impacted.", group: "Check", keywords: ["analytics","insights","trends","heatmap","cohort"] },
  { path: "/research", label: "Research", description: "Pull external context via Firecrawl to ground fixes in fresh docs.", group: "Check", keywords: ["firecrawl","web search","docs","scrape","crawl","knowledge"] },
  { path: "/experiments", label: "Experiments", description: "A/B experiments and feature flags.", group: "Check", keywords: ["experiments","ab","flags","variants"] },
  { path: "/iterate", label: "Iterate", description: "PDCA producer–critic improvement loop.", group: "Act", keywords: ["iterate","improve","loop"] },
  { path: "/skills", label: "Skill Pipelines", description: "Browse agent skills, track pipeline runs, and sync sources.", group: "Act", keywords: ["skills","skill pipelines","kenji skills","handoff","catalog","cursor-kenji"] },
  { path: "/integrations/config", label: "Integrations", description: "Connect services: Slack, Sentry, GitHub, Linear, Discord — tokens, webhooks, health.", group: "Act", keywords: ["slack","discord","github","sentry","linear","stripe","webhook","connect","plug","integrations","services"] },
  { path: "/mcp", label: "MCP", description: "Connect Cursor, Claude Desktop, and other MCP agents to this project.", group: "Act", keywords: ["mcp","claude","cursor","agent","tools","context","windsurf","agent help"] },
  { path: "/marketplace", label: "Marketplace", description: "Pre-built recipes and templates for common flows.", group: "Act", keywords: ["recipes","templates","install","plugins"] },
  { path: "/notifications", label: "Alert routing", description: "Route events to Slack, email, or Discord with per-stage rules.", group: "Act", keywords: ["alerts","email","slack","discord","routing","rules","digest","alert routing"] },
  { path: "/projects", label: "Projects", description: "Create, archive, and manage projects and members.", group: "Workspace", keywords: ["team","members","create project","organisation","workspace"] },
  { path: "/organization/members", label: "Members", description: "Invite teammates and manage organization roles.", group: "Workspace", keywords: ["members","invite","team","organization"] },
  { path: "/settings", label: "Settings", description: "Project configuration, API keys, Firecrawl, theming.", group: "Workspace", keywords: ["config","api key","preferences","firecrawl","theme","branding"] },
  { path: "/rewards", label: "Rewards", description: "Tester rewards and redemption catalog.", group: "Workspace", keywords: ["rewards","tester","bounty","wallet"] },
  { path: "/cost", label: "LLM Cost", description: "Token usage and LLM spend by stage.", group: "Workspace", keywords: ["cost","llm","tokens","billing","usage"] },
  { path: "/billing", label: "Billing", description: "Plan, seats, invoices, and usage-based charges.", group: "Workspace", keywords: ["stripe","plan","invoice","seats","usage","subscription","upgrade"] },
  { path: "/sso", label: "SSO", description: "Single sign-on, SAML, and identity provider setup.", group: "Workspace", keywords: ["saml","oidc","identity","login","auth"] },
  { path: "/compliance", label: "Compliance", description: "SOC 2, GDPR, and DSAR — evidence bundles and retention rules.", group: "Workspace", keywords: ["soc2","gdpr","dsar","privacy","retention","evidence","regulator"] },
  { path: "/audit", label: "Audit Log", description: "Forensic trail of every admin action with actor + diff.", group: "Workspace", keywords: ["log","history","forensic","security","changes","who did what"] },
  { path: "/storage", label: "Storage", description: "Bucket usage, screenshot retention, and data-lifecycle policies.", group: "Workspace", keywords: ["s3","bucket","screenshots","attachments","retention","lifecycle"] },
  { path: "/query", label: "Query", description: "Run read-only SQL against your project schema.", group: "Workspace", keywords: ["sql","postgres","ad-hoc","data","explorer"] },
  { path: "/users", label: "Users", description: "Operator-only user directory.", group: "Workspace", keywords: ["users","operators","directory"] },
  { path: "/setup-copilot", label: "Setup copilot", description: "Guided verify-and-dispatch setup assistant.", group: "Start", keywords: ["setup","copilot","verify","dispatch","guided"] },
  { path: "/cli-auth", label: "CLI auth", description: "OAuth handoff for the Mushi CLI.", group: "Act", keywords: ["cli","oauth","auth","terminal"] },
  { path: "/docs-bridge", label: "Docs bridge", description: "Open authenticated docs in a new tab.", group: "Workspace", keywords: ["docs","documentation","bridge","token"] },
  { path: "/skills", label: "Skill Catalog", description: "Browse 70+ agent skills from kenji skills by category.", group: "Act", keywords: ["catalog","skill catalog","cursor-kenji","kenji skills"] },
  { path: "/skills", label: "Skill Pipelines", description: "Track live pipeline runs and check in each step.", group: "Act", keywords: ["pipeline runs","handoff","context packet","checkin"] },
  { path: "/skills", label: "Skill Sources", description: "Add GitHub repos (e.g. kensaurus/skills) and sync SKILL.md files.", group: "Act", keywords: ["skill sources","skill sync","skills.sh","kenji skills","cursor-kenji"] },
]

export const CONSOLE_ROUTE_PATHS = new Set(CONSOLE_ROUTES.map((r) => r.path))

export function isValidConsoleRoute(path: string): boolean {
  const base = path.split('?')[0].split('#')[0]
  if (CONSOLE_ROUTE_PATHS.has(base)) return true
  // Dynamic segments: /reports/:id matches /reports/*
  return CONSOLE_ROUTES.some((r) => {
    if (!r.path.includes(':')) return false
    const prefix = r.path.split('/:')[0]
    return base.startsWith(prefix + '/') || base === prefix
  })
}
