/**
 * FILE: console-routes.generated.ts
 * PURPOSE: Canonical admin-console route directory for NL assistant nav validation.
 * GENERATED BY: scripts/build-console-knowledge.mjs — do not edit by hand.
 */

export interface ConsoleRouteEntry {
  path: string
  label: string
  description: string
  group: string
  keywords: string[]
}

export const CONSOLE_ROUTES: ConsoleRouteEntry[] = [
  { path: "/dashboard", label: "Dashboard", description: "Live PDCA loop — bugs in, fixes out, judge scores, shipped impact.", group: "Start", keywords: ["home","overview","kpi","metrics","loop","landing","summary"] },
  { path: "/onboarding", label: "Get started", description: "Three-step setup: create a project, install the widget, send a test bug.", group: "Start", keywords: ["setup","install","quickstart","first run","widget","snippet","project"] },
  { path: "/connect", label: "Connect & Update", description: "Connect GitHub, install SDK + MCP, and create upgrade PRs.", group: "Start", keywords: ["connect","install","sdk","upgrade","update","mcp","cursor","npm","package"] },
  { path: "/explore", label: "Explore codebase", description: "Map, chat with, and tour your indexed repository.", group: "Plan", keywords: ["codebase","atlas","understand","architecture","graph","ask","tour","domains"] },
  { path: "/inbox", label: "Inbox", description: "Action inbox — every event awaiting your decision in one place.", group: "Plan", keywords: ["inbox","action","todo","queue","notifications","unread","pending"] },
  { path: "/graph", label: "Graph", description: "Fingerprint graph — dedup clusters and shared root causes.", group: "Plan", keywords: ["cluster","dedup","fingerprint","similar bugs","network","visualisation","reactflow"] },
  { path: "/anti-gaming", label: "Anti-Gaming", description: "Spam, collusion, and duplicate-submission defences.", group: "Plan", keywords: ["spam","abuse","collusion","rate limit","fraud","dupes"] },
  { path: "/queue", label: "Queue", description: "Dead-letter queue for ingestion retries and poisoned events.", group: "Plan", keywords: ["dlq","dead letter","retry","failures","pipeline"] },
  { path: "/fixes", label: "Fixes", description: "Drafted pull requests from the auto-fix agent, ready to merge.", group: "Do", keywords: ["pull request","pr","patch","diff","merge","codex","llm","agent","drafts"] },
  { path: "/repo", label: "Repo", description: "Every auto-fix branch and PR across the connected GitHub repo, with CI status.", group: "Do", keywords: ["repo","repository","branch","branches","git","github","pr","pull request","ci","checks","merge","activity"] },
  { path: "/prompt-lab", label: "Prompt Lab", description: "Tune the prompts that turn reports into pull requests.", group: "Do", keywords: ["prompt","llm","model","ai","tuning","evals","template","system prompt"] },
  { path: "/judge", label: "Judge", description: "Independent quality grading for the auto-fix output.", group: "Check", keywords: ["score","eval","quality","grade","verification","llm-as-judge"] },
  { path: "/health", label: "Health", description: "System health — uptime, error rates, queue depth, backpressure.", group: "Check", keywords: ["status","uptime","availability","sentry","slo","monitoring","incidents"] },
  { path: "/code-health", label: "Code Health", description: "Bundle-size trends and god-file LOC findings pushed from host-repo CI.", group: "Check", keywords: ["bundle","loc","god file","refactor","gzip","code health","ci","budget","file size"] },
  { path: "/intelligence", label: "Intelligence", description: "Cross-project insights: what fails most, who is impacted.", group: "Check", keywords: ["analytics","insights","trends","heatmap","cohort"] },
  { path: "/research", label: "Research", description: "Pull external context via Firecrawl to ground fixes in fresh docs.", group: "Check", keywords: ["firecrawl","web search","docs","scrape","crawl","knowledge"] },
  { path: "/skills", label: "Skill Catalog", description: "Browse 70+ cursor-kenji agent skills by category — audit, test, enhance, workflow.", group: "Act", keywords: ["catalog","skill catalog","skills","skill pipelines","pipeline","pipelines","cursor-kenji","cursor","kenji","agent skills","workflow","audit","enhance","handoff","skill sync","sources","kenji skills"] },
  { path: "/skills", label: "Skill Pipelines", description: "Track live pipeline runs, copy handoff packets, and check in each step.", group: "Act", keywords: ["pipeline runs","skill pipeline","handoff","context packet","checkin","cursor agent","pipeline status","skills run"] },
  { path: "/skills", label: "Skill Sources", description: "Add GitHub repos (e.g. kensaurus/cursor-kenji) and sync SKILL.md files.", group: "Act", keywords: ["skill sources","skill sync","cursor-kenji","github repo","skills.sh"] },
  { path: "/integrations", label: "Integrations", description: "Connect Slack, Discord, GitHub, Sentry, Stripe, and more.", group: "Act", keywords: ["slack","discord","github","sentry","stripe","webhook","connect","plug"] },
  { path: "/mcp", label: "MCP", description: "Connect Cursor, Claude Desktop, and other MCP agents to this project.", group: "Act", keywords: ["mcp","claude","cursor","agent","tools","context","protocol","windsurf"] },
  { path: "/marketplace", label: "Marketplace", description: "Pre-built recipes and templates for common flows.", group: "Act", keywords: ["recipes","templates","install","plugins"] },
  { path: "/notifications", label: "Notifications", description: "Route events to Slack, email, or Discord with per-stage rules.", group: "Act", keywords: ["alerts","email","slack","discord","routing","rules","digest"] },
  { path: "/projects", label: "Projects", description: "Create, archive, and manage projects and members.", group: "Workspace", keywords: ["team","members","create project","organisation","workspace"] },
  { path: "/settings", label: "Settings", description: "Project configuration, API keys, Firecrawl, theming.", group: "Workspace", keywords: ["config","api key","preferences","firecrawl","theme","branding"] },
  { path: "/sso", label: "SSO", description: "Single sign-on, SAML, and identity provider setup.", group: "Workspace", keywords: ["saml","oidc","identity","login","auth"] },
  { path: "/billing", label: "Billing", description: "Plan, seats, invoices, and usage-based charges.", group: "Workspace", keywords: ["stripe","plan","invoice","seats","usage","subscription","upgrade"] },
  { path: "/audit", label: "Audit Log", description: "Forensic trail of every admin action with actor + diff.", group: "Workspace", keywords: ["log","history","forensic","security","changes","who did what"] },
  { path: "/compliance", label: "Compliance", description: "SOC 2, GDPR, and DSAR — evidence bundles and retention rules.", group: "Workspace", keywords: ["soc2","gdpr","dsar","privacy","retention","evidence","regulator"] },
  { path: "/storage", label: "Storage", description: "Bucket usage, screenshot retention, and data-lifecycle policies.", group: "Workspace", keywords: ["s3","bucket","screenshots","attachments","retention","lifecycle"] },
  { path: "/query", label: "Query", description: "Run read-only SQL against your project schema.", group: "Workspace", keywords: ["sql","postgres","ad-hoc","data","explorer"] },
  { path: "/content", label: "Content QA", description: "Review AI-generated and user-submitted content quality.", group: "Plan", keywords: ["content","qa","quality","moderation"] },
  { path: "/inventory", label: "User stories", description: "User-story inventory and live crawl proposals.", group: "Plan", keywords: ["stories","inventory","discovery","crawl"] },
  { path: "/qa-coverage", label: "QA Coverage", description: "Scheduled Playwright user-story tests.", group: "Check", keywords: ["qa","playwright","stories","coverage","test"] },
  { path: "/fullstack-audit", label: "Full-Stack Audit", description: "End-to-end audit across frontend, API, and database.", group: "Check", keywords: ["audit","fullstack","fe","be","schema"] },
  { path: "/lessons", label: "Lessons", description: "Patterns learned from past bugs and fixes.", group: "Check", keywords: ["lessons","learned","patterns","pdca"] },
  { path: "/drift", label: "Drift", description: "Schema and backend drift detection.", group: "Check", keywords: ["drift","schema","backend","migration"] },
  { path: "/anomalies", label: "Anomalies", description: "Statistical anomaly detection on metrics.", group: "Check", keywords: ["anomalies","spike","outlier","metrics"] },
  { path: "/releases", label: "Releases", description: "Shipped releases with reporter credit.", group: "Check", keywords: ["releases","changelog","ship","deploy"] },
  { path: "/iterate", label: "Iterate", description: "PDCA producer–critic improvement loop.", group: "Act", keywords: ["iterate","pdca","improve","loop"] },
  { path: "/rewards", label: "Rewards", description: "Tester rewards and redemption catalog.", group: "Workspace", keywords: ["rewards","tester","bounty","wallet"] },
  { path: "/cost", label: "LLM Cost", description: "Token usage and LLM spend by stage.", group: "Workspace", keywords: ["cost","llm","tokens","billing","usage"] },
  { path: "/feedback", label: "My feedback", description: "Feedback you submitted to Mushi.", group: "Start", keywords: ["feedback","feature","bug","request"] },
  { path: "/feature-board", label: "Feature board", description: "Community feature requests and votes.", group: "Start", keywords: ["features","roadmap","votes","board"] },
]

export const CONSOLE_ROUTE_PATHS = new Set(CONSOLE_ROUTES.map((r) => r.path))

export function isValidConsoleRoute(path: string): boolean {
  const base = path.split('?')[0].split('#')[0]
  if (CONSOLE_ROUTE_PATHS.has(base)) return true
  // Dynamic segments: /reports/:id matches /reports/*
  return CONSOLE_ROUTES.some((r) => {
    if (!r.path.includes(':')) return false
    const prefix = r.path.split('/:')[0]
    return base.startsWith(prefix + '/') || base === prefix
  })
}
