/**
 * FILE: console-routes.generated.ts
 * PURPOSE: Canonical admin-console route directory for NL assistant nav validation.
 * GENERATED BY: scripts/build-console-knowledge.mjs — do not edit by hand.
 */

export interface ConsoleRouteEntry {
  path: string
  label: string
  description: string
  group: string
  keywords: string[]
}

export const CONSOLE_ROUTES: ConsoleRouteEntry[] = [
  { path: "/onboarding", label: "Set up", description: "Three-step setup: create a project, install the widget, send a test bug.", group: "Start", keywords: ["get started","setup","install","quickstart","first run","widget","snippet","project"] },
  { path: "/dashboard", label: "Home", description: "Summary for the selected app: open bugs, fixes in progress, setup and recent activity.", group: "Start", keywords: ["dashboard","home","overview","kpi","metrics","loop","landing","summary"] },
  { path: "/inbox", label: "To-do", description: "One card for each decision waiting on you — bugs to triage, fixes to review, setup to finish.", group: "Start", keywords: ["action inbox","inbox","action","todo","to do","pending","decision","next"] },
  { path: "/portfolio", label: "All apps", description: "Every app in this team side by side: setup state, open bugs, SDK version and problems to fix once across apps.", group: "Start", keywords: ["portfolio","all apps","apps","fix once","sdk skew","sdk version","radar","holes","team","organization"] },
  { path: "/overview", label: "App activity", description: "Last 7 days for every app in this team: sessions, users and open bugs, with links into each app.", group: "Start", keywords: ["overview","portfolio view","all projects","activity","sessions","consolidated"] },
  { path: "/connect", label: "Connect", description: "Wire up your editor and app: SDK install, MCP for Cursor/Claude, upgrade PRs.", group: "Start", keywords: ["connect & update","install","sdk","upgrade","update","mcp","cursor","npm","package","editor"] },
  { path: "/feedback", label: "Help & support", description: "Ask the Mushi team for help and read their replies to feedback you sent.", group: "Start", keywords: ["support","feedback","help","contact","bug","request"] },
  { path: "/feature-board", label: "Feature requests", description: "Community feature requests and votes.", group: "Start", keywords: ["feature board","features","roadmap","votes","board"] },
  { path: "/reports", label: "Bugs", description: "Every bug report from your users — search, filter, sort and open one to fix it.", group: "Plan", keywords: ["reports","bugs to fix","bug reports","triage","complaints","issues","incidents","tickets"] },
  { path: "/graph", label: "Bug clusters", description: "Bugs grouped by shared cause, so one fix can close several reports.", group: "Plan", keywords: ["graph","cluster","dedup","duplicates","fingerprint","similar bugs","root cause","network"] },
  { path: "/inventory", label: "User stories", description: "The things users can do in your app, found by crawling it, and which ones broke.", group: "Plan", keywords: ["stories","inventory","discovery","crawl","user stories"] },
  { path: "/content", label: "Content checks", description: "Review AI-generated and user-submitted content flagged as wrong or low quality.", group: "Plan", keywords: ["content qa","content","qa","quality","moderation"] },
  { path: "/explore", label: "Code map", description: "Map, ask questions about, and tour your indexed repository.", group: "Plan", keywords: ["explore","codebase","atlas","understand","architecture","ask","tour","domains","codebase map"] },
  { path: "/queue", label: "Processing jobs", description: "Background jobs that read and sort new reports; retry the ones that failed.", group: "Plan", keywords: ["failed events","queue","dlq","dead letter","retry","failures","pipeline","jobs"] },
  { path: "/anti-gaming", label: "Spam & abuse", description: "Catch spam, duplicate submissions and testers gaming the rewards.", group: "Plan", keywords: ["anti-gaming","anti gaming","spam","abuse","collusion","rate limit","fraud","dupes"] },
  { path: "/fixes", label: "Fixes", description: "Draft pull requests written by the fix agent, with their checks, ready to review and merge.", group: "Do", keywords: ["fixes ready","pull request","pr","patch","diff","merge","codex","llm","agent","drafts"] },
  { path: "/repo", label: "Pull requests", description: "Every fix branch and pull request in your connected GitHub repo, with CI status.", group: "Do", keywords: ["repo","repository","branch","branches","git","github","pr","pull request","ci","checks","merge","activity"] },
  { path: "/voice", label: "Voice reports", description: "Talk a bug or a fix request from your phone; confirm the transcript; the draft PR comes back as a push.", group: "Do", keywords: ["voice","mic","microphone","record","dictate","phone","audio","telegram","push","notify","pwa"] },
  { path: "/prompt-lab", label: "AI prompts", description: "Edit and compare the prompts that turn bug reports into pull requests.", group: "Do", keywords: ["prompt lab","prompt","llm","model","ai","tuning","evals","template","system prompt"] },
  { path: "/iterate", label: "Improvement runs", description: "Runs where one AI drafts a change and a second AI critiques it until it passes — for fixes, prompts and tests.", group: "Do", keywords: ["iterate","pdca","improve","loop","producer critic","runs"] },
  { path: "/judge", label: "Fix grading", description: "A second AI grades each automatic fix and flags where it disagrees with the first.", group: "Check", keywords: ["judge","score","eval","quality","grade","grading","verification","llm-as-judge"] },
  { path: "/qa-coverage", label: "Scheduled tests", description: "Browser tests of your user stories that run on a schedule and alert when one breaks.", group: "Check", keywords: ["qa coverage","qa","playwright","stories","coverage","test","tests"] },
  { path: "/fullstack-audit", label: "Full-stack audit", description: "End-to-end audit across frontend, API, and database.", group: "Check", keywords: ["full-stack audit","audit","fullstack","fe","be","schema"] },
  { path: "/lessons", label: "Lessons", description: "Patterns learned from past bugs and fixes.", group: "Check", keywords: ["lessons","learned","patterns"] },
  { path: "/design", label: "Design system", description: "Design tokens, contrast pairs, type scale and the deviance score for off-token code; token and rule edits open a draft PR.", group: "Check", keywords: ["design","design system","tokens","dtcg","colors","contrast","typography","spacing","radius","deviance","off-token","rules"] },
  { path: "/health", label: "System health", description: "Are your integrations and background jobs working: uptime, errors and failed checks.", group: "Check", keywords: ["health","status","uptime","availability","sentry","slo","monitoring","incidents","verification hub"] },
  { path: "/code-health", label: "Code size", description: "Bundle-size trends and very large files, pushed from your repo’s CI.", group: "Check", keywords: ["code health","bundle","loc","god file","refactor","gzip","ci","budget","file size"] },
  { path: "/recipe", label: "App blueprint", description: "What this app is built from — database, design system, routes, CI, deploy, env and integrations — and what changed.", group: "Check", keywords: ["recipe","app recipe","blueprint","stack","design system","tokens","gates","ci","deploy","env","integrations","manifest","mushi.recipe.json"] },
  { path: "/drift", label: "Schema changes", description: "Your database schema compared with the last scan: dropped columns, missing access rules, unexpected changes.", group: "Check", keywords: ["drift","schema","backend","migration","database"] },
  { path: "/anomalies", label: "Unusual spikes", description: "Sudden jumps in errors or reports, including ones that started with a release.", group: "Check", keywords: ["anomalies","anomaly","spike","outlier","metrics"] },
  { path: "/activity", label: "User activity", description: "Per-app activity — sessions, page views, identified vs. anonymous users, top routes.", group: "Check", keywords: ["activity","sessions","users","page views","analytics","dau","engagement"] },
  { path: "/analytics", label: "Users & funnels", description: "Product analytics from Mushi.track() — event volume, funnels, next-step paths, people, and weekly retention.", group: "Check", keywords: ["users & funnels","funnel","funnels","events","track","analytics","retention","paths","people","conversion","cohort"] },
  { path: "/releases", label: "Releases", description: "Shipped releases with reporter credit.", group: "Check", keywords: ["releases","changelog","ship","deploy"] },
  { path: "/intelligence", label: "Weekly insights", description: "A weekly plain-English report across your apps: what breaks most and who it hits.", group: "Check", keywords: ["intelligence","insights","analytics","trends","heatmap","cohort","weekly report"] },
  { path: "/research", label: "Research", description: "Pull web pages and docs (via Firecrawl) into a fix so it uses current information.", group: "Check", keywords: ["research","firecrawl","web search","docs","scrape","crawl","knowledge"] },
  { path: "/experiments", label: "Experiments", description: "A/B experiments and feature flags.", group: "Check", keywords: ["experiments","ab","a/b","flags","variants"] },
  { path: "/growth", label: "Growth", description: "Operator-only company funnel — activated external projects per week, by signup source.", group: "Check", keywords: ["growth","funnel","signups","activation","activated","paid","source","operator"] },
  { path: "/integrations/config", label: "Integrations", description: "Connect services: Slack, Sentry, GitHub, Linear, Discord — tokens, webhooks, health.", group: "Act", keywords: ["slack","discord","github","sentry","linear","stripe","webhook","connect","plug","integrations","services"] },
  { path: "/mcp", label: "Editor agents", description: "Connect Cursor, Claude and other coding agents to this app through MCP.", group: "Act", keywords: ["mcp","agent help","claude","cursor","agent","tools","context","windsurf","editor"] },
  { path: "/skills", label: "Agent skills", description: "Browse agent skills, track the runs that use them, and sync skill sources.", group: "Act", keywords: ["skills","skill pipelines","skill catalog","kenji skills","handoff","catalog","cursor-kenji"] },
  { path: "/notifications", label: "Alert routing", description: "Choose which events go to Slack, email or Discord, and when.", group: "Act", keywords: ["alerts","notifications","email","slack","discord","routing","rules","digest","alert routing"] },
  { path: "/marketplace", label: "Plugins", description: "Install plugins and ready-made templates for common flows.", group: "Act", keywords: ["marketplace","recipes","templates","install","plugins"] },
  { path: "/projects", label: "Manage apps", description: "Create, rename and archive apps (projects), and see their keys and setup.", group: "Workspace", keywords: ["projects","apps","create project","new app","team","members","organisation","workspace"] },
  { path: "/organization/members", label: "Team members", description: "Invite teammates and manage their roles.", group: "Workspace", keywords: ["members","invite","team","organization","roles"] },
  { path: "/settings", label: "Settings", description: "Project settings: your AI keys, alerts, web research, voice and health check.", group: "Workspace", keywords: ["settings","config","api key","api keys","ai keys","your ai keys","byok","bring your own key","anthropic","openai","keys","preferences","firecrawl","web research","browserbase","cloud browser","voice","health check","theme","branding"] },
  { path: "/billing", label: "Billing", description: "Plan, seats, invoices, and usage-based charges.", group: "Workspace", keywords: ["billing","stripe","plan","invoice","seats","usage","subscription","upgrade"] },
  { path: "/cost", label: "AI spend", description: "What the AI behind diagnoses and fixes costs, by step and day.", group: "Workspace", keywords: ["llm cost","cost","llm","tokens","spend","usage"] },
  { path: "/rewards", label: "Tester rewards", description: "Points, tiers and payouts for the people who report bugs.", group: "Workspace", keywords: ["rewards","tester","bounty","wallet","points"] },
  { path: "/sso", label: "Single sign-on", description: "Single sign-on, SAML, and identity provider setup.", group: "Workspace", keywords: ["sso","saml","oidc","identity","login","auth"] },
  { path: "/compliance", label: "Compliance", description: "SOC 2, GDPR, and DSAR — evidence bundles and retention rules.", group: "Workspace", keywords: ["compliance","soc2","gdpr","dsar","privacy","retention","evidence","regulator"] },
  { path: "/audit", label: "Audit log", description: "Who changed what in this console, and when.", group: "Workspace", keywords: ["audit log","log","history","forensic","security","changes","who did what"] },
  { path: "/storage", label: "Storage", description: "Bucket usage, screenshot retention, and data-lifecycle policies.", group: "Workspace", keywords: ["storage","s3","bucket","screenshots","attachments","retention","lifecycle"] },
  { path: "/query", label: "SQL query", description: "Run read-only SQL against your project schema.", group: "Workspace", keywords: ["query","sql","postgres","ad-hoc","data","explorer"] },
  { path: "/users", label: "All users", description: "Operator-only user directory.", group: "Workspace", keywords: ["users","operators","directory"] },
  { path: "/setup-copilot", label: "Setup copilot", description: "Guided verify-and-dispatch setup assistant.", group: "Start", keywords: ["setup","copilot","verify","dispatch","guided"] },
  { path: "/cli-auth", label: "CLI sign-in", description: "Approve the Mushi CLI sign-in from your terminal.", group: "Act", keywords: ["cli auth","cli","oauth","auth","terminal","login"] },
  { path: "/docs-bridge", label: "Docs", description: "Open the documentation, signed in, in a new tab.", group: "Workspace", keywords: ["docs bridge","docs","documentation","bridge","token"] },
  { path: "/skills", label: "Skill catalog", description: "Browse 70+ agent skills from kenji skills by category.", group: "Act", keywords: ["catalog","skill catalog","cursor-kenji","kenji skills"] },
  { path: "/skills", label: "Skill runs", description: "Track live skill pipeline runs and check in each step.", group: "Act", keywords: ["skill pipelines","pipeline runs","handoff","context packet","checkin"] },
  { path: "/skills", label: "Skill sources", description: "Add GitHub repos (e.g. kensaurus/skills) and sync SKILL.md files.", group: "Act", keywords: ["skill sources","skill sync","skills.sh","kenji skills","cursor-kenji"] },
]

export const CONSOLE_ROUTE_PATHS = new Set(CONSOLE_ROUTES.map((r) => r.path))

export function isValidConsoleRoute(path: string): boolean {
  const base = path.split('?')[0].split('#')[0]
  if (CONSOLE_ROUTE_PATHS.has(base)) return true
  // Dynamic segments: /reports/:id matches /reports/*
  return CONSOLE_ROUTES.some((r) => {
    if (!r.path.includes(':')) return false
    const prefix = r.path.split('/:')[0]
    return base.startsWith(prefix + '/') || base === prefix
  })
}
