/**
 * FILE: packages/server/supabase/functions/_shared/deploy-info.ts
 * PURPOSE: Deploy-time build stamp for the hosted MCP server's
 *          `serverInfo.version` (production-readiness audit, Tier 2 item
 *          #12 — "hardcoded serverInfo.version never tracks real deploys").
 *
 * `scripts/deploy-edge-function.mjs` overwrites the two values below with
 * the real commit SHA + deploy timestamp on disk, immediately before
 * bundling `_shared/` for upload — every function deploy gets the same
 * stamp since they all bundle the same `_shared/` tree. This file is NOT
 * regenerated by a git hook and the overwritten values are never committed
 * back; `sha: 'dev'` is the checked-in default so local dev
 * (`supabase functions serve`, `deno check`) and this file's own history
 * stay clean.
 *
 * Consumed by `_shared/mcp-branding.ts` to compose
 * `${baseVersion}+${shortSha}` — clients can now tell two deploys apart
 * even when the hand-maintained base version hasn't changed, which is
 * exactly the gap the audit flagged (stdio's `@mushi-mushi/mcp` already
 * gets this for free by reading `package.json` at publish time; the hosted
 * transport has no equivalent npm-publish step to hook into).
 */
export const DEPLOY_INFO: { sha: string; deployedAt: string | null } = {
  sha: 'dev',
  deployedAt: null,
}
