/**
 * FILE: apps/admin/src/lib/sdkSnippets.test.ts
 * PURPOSE: Lock down the per-framework init snippets generated by the
 *          live SDK configurator. These contracts exist because we shipped
 *          a regression where the Vue/Svelte snippets dropped the
 *          `Mushi.init()` call from `@mushi-mushi/web` — leaving users
 *          with an installed-but-unused package and no visual widget
 *          mounted in their app, while configurator settings for
 *          position/theme/capture were silently ignored.
 *
 *          Each test below pins one half of the framework adapter contract:
 *
 *            • Vue/Svelte adapters accept ONLY { projectId, apiKey, endpoint? }.
 *              They wire composables + framework error handlers, not UI.
 *              See packages/vue/src/index.ts:14 + packages/svelte/src/index.ts:12.
 *
 *            • The visual bug-capture widget (floating button + modal +
 *              console/network capture) is mounted by `Mushi.init()` from
 *              `@mushi-mushi/web`. Anything the configurator exposes
 *              (widget.position, widget.theme, capture.*) MUST flow into
 *              that call — never into MushiPlugin/initMushi.
 *
 *          If a future refactor splits these snippets again, these tests
 *          will fail before any user does.
 */

import { describe, expect, it } from 'vitest'
import {
  DEFAULT_SDK_CONFIG,
  FRAMEWORKS,
  installCommand,
  isMobileFramework,
  MOBILE_FRAMEWORKS,
  renderSnippet,
  type SdkPreviewConfig,
} from './sdkSnippets'

const PROJECT = 'proj_abc'
const KEY = 'mushi_secret_xyz'

const tweakedConfig: SdkPreviewConfig = {
  ...DEFAULT_SDK_CONFIG,
  position: 'top-left',
  theme: 'dark',
  capture: { ...DEFAULT_SDK_CONFIG.capture, console: false, screenshot: 'auto' },
}

describe('renderSnippet — Vue', () => {
  it('imports both the Vue plugin AND @mushi-mushi/web for the widget', () => {
    const out = renderSnippet('vue', PROJECT, KEY)
    expect(out).toContain("import { MushiPlugin } from '@mushi-mushi/vue'")
    expect(out).toContain("import { Mushi } from '@mushi-mushi/web'")
  })

  it('emits BOTH app.use(MushiPlugin, …) AND Mushi.init(…) — neither is optional', () => {
    const out = renderSnippet('vue', PROJECT, KEY)
    expect(out).toMatch(/app\.use\(MushiPlugin,/)
    expect(out).toMatch(/Mushi\.init\(/)
  })

  it('routes widget/capture tweaks to Mushi.init(), NEVER to MushiPlugin', () => {
    const out = renderSnippet('vue', PROJECT, KEY, tweakedConfig)
    // The configurator settings must appear AFTER the Mushi.init( call site,
    // not before it (where MushiPlugin lives). Splitting on Mushi.init lets
    // us assert that boundary without overfitting to whitespace.
    const [beforeMushiInit, afterMushiInit] = out.split('Mushi.init(')
    expect(afterMushiInit).toBeDefined()
    expect(afterMushiInit).toContain("position: 'top-left'")
    expect(afterMushiInit).toContain("theme: 'dark'")
    expect(afterMushiInit).toContain('console: false')
    expect(afterMushiInit).toContain("screenshot: 'auto'")
    // And critically: none of those configurator keys are passed to
    // MushiPlugin (where the Vue adapter would silently drop them).
    expect(beforeMushiInit).not.toContain('position:')
    expect(beforeMushiInit).not.toContain('theme:')
    expect(beforeMushiInit).not.toContain('capture:')
    expect(beforeMushiInit).not.toContain('widget:')
  })

  it('bakes projectId + apiKey in once and reuses them for both calls', () => {
    const out = renderSnippet('vue', PROJECT, KEY)
    expect(out).toContain(`projectId: '${PROJECT}'`)
    expect(out).toContain(`apiKey: '${KEY}'`)
    // We define `credentials` once and pass it to both MushiPlugin and
    // Mushi.init so a user who rotates keys has one place to update.
    expect(out).toContain('const credentials =')
  })

  it('falls back to the placeholder API key when one is not yet generated', () => {
    const out = renderSnippet('vue', PROJECT, null)
    expect(out).toContain("apiKey: 'mushi_xxx'")
  })
})

describe('renderSnippet — Svelte', () => {
  it('imports both the Svelte adapter AND @mushi-mushi/web for the widget', () => {
    const out = renderSnippet('svelte', PROJECT, KEY)
    expect(out).toContain("import { initMushi } from '@mushi-mushi/svelte'")
    expect(out).toContain("import { Mushi } from '@mushi-mushi/web'")
  })

  it('emits BOTH initMushi(…) AND Mushi.init(…) — neither is optional', () => {
    const out = renderSnippet('svelte', PROJECT, KEY)
    expect(out).toMatch(/initMushi\(/)
    expect(out).toMatch(/Mushi\.init\(/)
  })

  it('routes widget/capture tweaks to Mushi.init(), NEVER to initMushi', () => {
    const out = renderSnippet('svelte', PROJECT, KEY, tweakedConfig)
    const beforeMushiInit = out.split('Mushi.init(')[0]
    const afterMushiInit = out.split('Mushi.init(')[1]
    expect(afterMushiInit).toContain("position: 'top-left'")
    expect(afterMushiInit).toContain("theme: 'dark'")
    expect(afterMushiInit).toContain('console: false')
    // initMushi() above must stay narrow — anything else is silently
    // dropped by the Svelte adapter (see packages/svelte/src/index.ts:12).
    const initMushiBlock = beforeMushiInit.slice(beforeMushiInit.indexOf('initMushi('))
    expect(initMushiBlock).not.toContain('position:')
    expect(initMushiBlock).not.toContain('theme:')
    expect(initMushiBlock).not.toContain('capture:')
    expect(initMushiBlock).not.toContain('widget:')
  })
})

describe('renderSnippet — React', () => {
  it('uses MushiProvider from @mushi-mushi/react which mounts the widget itself', () => {
    const out = renderSnippet('react', PROJECT, KEY, tweakedConfig)
    expect(out).toContain("import { MushiProvider } from '@mushi-mushi/react'")
    // React's provider already calls Mushi.init under the hood
    // (packages/react/src/provider.tsx:31), so the snippet should NOT
    // also import @mushi-mushi/web — that would be a double-mount.
    expect(out).not.toContain("from '@mushi-mushi/web'")
    // Tweaks flow straight into the MushiProvider config prop.
    expect(out).toContain("position: 'top-left'")
    expect(out).toContain("theme: 'dark'")
  })
})

describe('renderSnippet — Vanilla', () => {
  it('uses a single Mushi.init() call carrying the entire config', () => {
    const out = renderSnippet('vanilla', PROJECT, KEY, tweakedConfig)
    expect(out).toContain("import { Mushi } from '@mushi-mushi/web'")
    expect(out).toMatch(/Mushi\.init\(\{/)
    expect(out).toContain("position: 'top-left'")
    expect(out).toContain('console: false')
  })
})

/**
 * Regression: the live preview renders an empty triggerText input as the
 * default 🐛 (`config.triggerText.trim() ? config.triggerText : '\u{1F41B}'`
 * in SdkInstallCard.tsx — note the `.trim()`, which is what makes the
 * whitespace-only case below WYSIWYG-faithful), so the generated snippet
 * MUST also treat empty as "use default" — not emit `triggerText: ""` and
 * ship the user a literal invisible button.
 *
 * Whitespace-only input ("   ") behaves the same way: previously the bare
 * `||` in the preview let `"   "` through as truthy and rendered three
 * invisible spaces, while the snippet (this file) correctly omitted the
 * field. Both sides now share the same trim-then-fallback rule.
 *
 * Tested across all four framework adapters because every one of them
 * passes through `widgetLines` and the bug would have surfaced
 * identically in each.
 */
/**
 * Mobile / hybrid framework snippets.
 *
 * The Capacitor snippet had a regression where the CLI emitted `Mushi.init(...)`
 * but the actual API has always been `Mushi.configure(...)` (see
 * packages/capacitor/src/definitions.ts). Anyone copy-pasting the snippet
 * landed on a `TypeError: Mushi.init is not a function`. Locking the right
 * call site here so we never re-ship that bug from the admin console either.
 *
 * Same idea for React Native / Expo: pin that we use `<MushiProvider>` from
 * `@mushi-mushi/react-native` with top-level `projectId`/`apiKey` props (NOT
 * the imaginary `enableShakeToReport` from older docs), and that the install
 * line for Expo routes through `npx expo install` so peer-dep ranges stay
 * Expo-SDK-aligned.
 */
describe('renderSnippet — mobile / hybrid frameworks', () => {
  it('react-native uses <MushiProvider> with top-level projectId + apiKey', () => {
    const out = renderSnippet('react-native', PROJECT, KEY)
    expect(out).toContain("import { MushiProvider } from '@mushi-mushi/react-native'")
    expect(out).toMatch(/<MushiProvider[\s\S]*projectId="proj_abc"[\s\S]*apiKey="mushi_secret_xyz"/)
    expect(out).not.toContain('enableShakeToReport')
  })

  it('expo emits the same provider but mentions expo-sensors / npx expo install', () => {
    const out = renderSnippet('expo', PROJECT, KEY)
    expect(out).toContain('@mushi-mushi/react-native')
    expect(out).toMatch(/<MushiProvider[\s\S]*projectId="proj_abc"/)
    expect(out).toContain('expo-sensors')
    expect(installCommand('expo')).toContain('npx expo install')
  })

  it('capacitor calls Mushi.configure (NEVER Mushi.init) and reminds users to cap sync', () => {
    const out = renderSnippet('capacitor', PROJECT, KEY)
    expect(out).toContain("import { Mushi } from '@mushi-mushi/capacitor'")
    expect(out).toMatch(/await\s+Mushi\.configure\(/)
    expect(out).not.toMatch(/Mushi\.init\(/)
    expect(installCommand('capacitor')).toContain('cap sync')
  })

  it('mobile snippets reflect the configurator native.triggerMode', () => {
    const cfg: SdkPreviewConfig = {
      ...DEFAULT_SDK_CONFIG,
      native: { ...DEFAULT_SDK_CONFIG.native, triggerMode: 'shake' },
    }
    expect(renderSnippet('react-native', PROJECT, KEY, cfg)).toContain("trigger: 'shake'")
    expect(renderSnippet('capacitor', PROJECT, KEY, cfg)).not.toContain('triggerMode:')
  })

  /**
   * `triggerMode: 'none'` round-trip — pin both fixes against regression.
   *
   * Bug 1 (RN/Expo): MushiRNConfig.widget.trigger does NOT include 'none'
   *   (see packages/react-native/src/provider.tsx). Before the fix, the
   *   snippet emitted `trigger: 'none'`, which TypeScript rejects against
   *   the real SDK. The web SDK's mergeRuntimeConfig already canonicalises
   *   'none' → 'manual' at packages/web/src/mushi.ts:619-621, so the
   *   snippet must do the same. Asserting the SDK-valid 'manual' (and
   *   explicitly NOT the SDK-invalid 'none') both ways round.
   *
   * Bug 2 (Capacitor): MushiTriggerMode IS a 4-member union including
   *   'none' (packages/capacitor/src/definitions.ts:11). Before the fix,
   *   the snippet coerced 'none' → null, dropped the line entirely, and
   *   the runtime default 'shake' silently took over — the OPPOSITE of
   *   what the user picked. Pin that 'none' is emitted verbatim AND that
   *   the snippet does NOT silently fall back to shake (no missing line).
   */
  it("rn/expo: triggerMode 'none' becomes 'manual' (the SDK-valid equivalent)", () => {
    const cfg: SdkPreviewConfig = {
      ...DEFAULT_SDK_CONFIG,
      native: { ...DEFAULT_SDK_CONFIG.native, triggerMode: 'none' },
    }
    for (const fw of ['react-native', 'expo'] as const) {
      const out = renderSnippet(fw, PROJECT, KEY, cfg)
      expect(out).toContain("trigger: 'manual'")
      expect(out).not.toContain("trigger: 'none'")
    }
  })

  it("capacitor: triggerMode 'none' is emitted verbatim, NOT silently dropped to default 'shake'", () => {
    const cfg: SdkPreviewConfig = {
      ...DEFAULT_SDK_CONFIG,
      native: { ...DEFAULT_SDK_CONFIG.native, triggerMode: 'none' },
    }
    const out = renderSnippet('capacitor', PROJECT, KEY, cfg)
    expect(out).toContain("triggerMode: 'none'")
    /* Sanity: the line wasn't dropped. If a future refactor reintroduces
     * the 'none' → null coercion, this assertion keeps biting. */
    expect(out).toMatch(/triggerMode:\s*'none'/)
  })

  it("capacitor: every non-default triggerMode is emitted (button + both + none, but NOT shake)", () => {
    /* Property-style sanity: the implicit-default optimisation only applies
     * to 'shake'. Every other valid MushiTriggerMode value must round-trip
     * into the snippet, otherwise users lose explicit configuration silently. */
    for (const mode of ['button', 'both', 'none'] as const) {
      const cfg: SdkPreviewConfig = {
        ...DEFAULT_SDK_CONFIG,
        native: { ...DEFAULT_SDK_CONFIG.native, triggerMode: mode },
      }
      expect(renderSnippet('capacitor', PROJECT, KEY, cfg)).toContain(`triggerMode: '${mode}'`)
    }
    const shakeCfg: SdkPreviewConfig = {
      ...DEFAULT_SDK_CONFIG,
      native: { ...DEFAULT_SDK_CONFIG.native, triggerMode: 'shake' },
    }
    expect(renderSnippet('capacitor', PROJECT, KEY, shakeCfg)).not.toContain('triggerMode:')
  })

  it('every declared framework has an install command and a non-empty snippet', () => {
    for (const fw of FRAMEWORKS) {
      expect(installCommand(fw).length).toBeGreaterThan(0)
      expect(renderSnippet(fw, PROJECT, KEY).length).toBeGreaterThan(0)
    }
  })

  it('isMobileFramework() agrees with the MOBILE_FRAMEWORKS set', () => {
    for (const fw of FRAMEWORKS) {
      expect(isMobileFramework(fw)).toBe((MOBILE_FRAMEWORKS as readonly string[]).includes(fw))
    }
  })
})

describe('renderSnippet — empty triggerText (WYSIWYG with the preview)', () => {
  for (const fw of ['react', 'vue', 'svelte', 'vanilla'] as const) {
    it(`omits triggerText entirely when the input is empty (${fw})`, () => {
      const out = renderSnippet(fw, PROJECT, KEY, { ...DEFAULT_SDK_CONFIG, triggerText: '' })
      expect(out).not.toContain('triggerText')
    })

    it(`omits triggerText entirely when the input is whitespace-only (${fw})`, () => {
      const out = renderSnippet(fw, PROJECT, KEY, { ...DEFAULT_SDK_CONFIG, triggerText: '   ' })
      expect(out).not.toContain('triggerText')
    })

    it(`still emits triggerText when the user typed a real override (${fw})`, () => {
      const out = renderSnippet(fw, PROJECT, KEY, { ...DEFAULT_SDK_CONFIG, triggerText: 'Report' })
      expect(out).toContain('triggerText: "Report"')
    })
  }
})
