/**
 * FILE: apps/admin/src/lib/sdkSnippets.test.ts
 * PURPOSE: Lock down the per-framework init snippets generated by the
 *          live SDK configurator. These contracts exist because we shipped
 *          a regression where the Vue/Svelte snippets dropped the
 *          `Mushi.init()` call from `@mushi-mushi/web` — leaving users
 *          with an installed-but-unused package and no visual widget
 *          mounted in their app, while configurator settings for
 *          position/theme/capture were silently ignored.
 *
 *          Each test below pins one half of the framework adapter contract:
 *
 *            • Vue/Svelte adapters accept ONLY { projectId, apiKey, endpoint? }.
 *              They wire composables + framework error handlers, not UI.
 *              See packages/vue/src/index.ts:14 + packages/svelte/src/index.ts:12.
 *
 *            • The visual bug-capture widget (floating button + modal +
 *              console/network capture) is mounted by `Mushi.init()` from
 *              `@mushi-mushi/web`. Anything the configurator exposes
 *              (widget.position, widget.theme, capture.*) MUST flow into
 *              that call — never into MushiPlugin/initMushi.
 *
 *          If a future refactor splits these snippets again, these tests
 *          will fail before any user does.
 */

import { describe, expect, it } from 'vitest'
import { DEFAULT_SDK_CONFIG, renderSnippet, type SdkPreviewConfig } from './sdkSnippets'

const PROJECT = 'proj_abc'
const KEY = 'mushi_secret_xyz'

const tweakedConfig: SdkPreviewConfig = {
  ...DEFAULT_SDK_CONFIG,
  position: 'top-left',
  theme: 'dark',
  capture: { ...DEFAULT_SDK_CONFIG.capture, console: false, screenshot: 'auto' },
}

describe('renderSnippet — Vue', () => {
  it('imports both the Vue plugin AND @mushi-mushi/web for the widget', () => {
    const out = renderSnippet('vue', PROJECT, KEY)
    expect(out).toContain("import { MushiPlugin } from '@mushi-mushi/vue'")
    expect(out).toContain("import { Mushi } from '@mushi-mushi/web'")
  })

  it('emits BOTH app.use(MushiPlugin, …) AND Mushi.init(…) — neither is optional', () => {
    const out = renderSnippet('vue', PROJECT, KEY)
    expect(out).toMatch(/app\.use\(MushiPlugin,/)
    expect(out).toMatch(/Mushi\.init\(/)
  })

  it('routes widget/capture tweaks to Mushi.init(), NEVER to MushiPlugin', () => {
    const out = renderSnippet('vue', PROJECT, KEY, tweakedConfig)
    // The configurator settings must appear AFTER the Mushi.init( call site,
    // not before it (where MushiPlugin lives). Splitting on Mushi.init lets
    // us assert that boundary without overfitting to whitespace.
    const [beforeMushiInit, afterMushiInit] = out.split('Mushi.init(')
    expect(afterMushiInit).toBeDefined()
    expect(afterMushiInit).toContain("position: 'top-left'")
    expect(afterMushiInit).toContain("theme: 'dark'")
    expect(afterMushiInit).toContain('console: false')
    expect(afterMushiInit).toContain("screenshot: 'auto'")
    // And critically: none of those configurator keys are passed to
    // MushiPlugin (where the Vue adapter would silently drop them).
    expect(beforeMushiInit).not.toContain('position:')
    expect(beforeMushiInit).not.toContain('theme:')
    expect(beforeMushiInit).not.toContain('capture:')
    expect(beforeMushiInit).not.toContain('widget:')
  })

  it('bakes projectId + apiKey in once and reuses them for both calls', () => {
    const out = renderSnippet('vue', PROJECT, KEY)
    expect(out).toContain(`projectId: '${PROJECT}'`)
    expect(out).toContain(`apiKey: '${KEY}'`)
    // We define `credentials` once and pass it to both MushiPlugin and
    // Mushi.init so a user who rotates keys has one place to update.
    expect(out).toContain('const credentials =')
  })

  it('falls back to the placeholder API key when one is not yet generated', () => {
    const out = renderSnippet('vue', PROJECT, null)
    expect(out).toContain("apiKey: 'mushi_xxx'")
  })
})

describe('renderSnippet — Svelte', () => {
  it('imports both the Svelte adapter AND @mushi-mushi/web for the widget', () => {
    const out = renderSnippet('svelte', PROJECT, KEY)
    expect(out).toContain("import { initMushi } from '@mushi-mushi/svelte'")
    expect(out).toContain("import { Mushi } from '@mushi-mushi/web'")
  })

  it('emits BOTH initMushi(…) AND Mushi.init(…) — neither is optional', () => {
    const out = renderSnippet('svelte', PROJECT, KEY)
    expect(out).toMatch(/initMushi\(/)
    expect(out).toMatch(/Mushi\.init\(/)
  })

  it('routes widget/capture tweaks to Mushi.init(), NEVER to initMushi', () => {
    const out = renderSnippet('svelte', PROJECT, KEY, tweakedConfig)
    const beforeMushiInit = out.split('Mushi.init(')[0]
    const afterMushiInit = out.split('Mushi.init(')[1]
    expect(afterMushiInit).toContain("position: 'top-left'")
    expect(afterMushiInit).toContain("theme: 'dark'")
    expect(afterMushiInit).toContain('console: false')
    // initMushi() above must stay narrow — anything else is silently
    // dropped by the Svelte adapter (see packages/svelte/src/index.ts:12).
    const initMushiBlock = beforeMushiInit.slice(beforeMushiInit.indexOf('initMushi('))
    expect(initMushiBlock).not.toContain('position:')
    expect(initMushiBlock).not.toContain('theme:')
    expect(initMushiBlock).not.toContain('capture:')
    expect(initMushiBlock).not.toContain('widget:')
  })
})

describe('renderSnippet — React', () => {
  it('uses MushiProvider from @mushi-mushi/react which mounts the widget itself', () => {
    const out = renderSnippet('react', PROJECT, KEY, tweakedConfig)
    expect(out).toContain("import { MushiProvider } from '@mushi-mushi/react'")
    // React's provider already calls Mushi.init under the hood
    // (packages/react/src/provider.tsx:31), so the snippet should NOT
    // also import @mushi-mushi/web — that would be a double-mount.
    expect(out).not.toContain("from '@mushi-mushi/web'")
    // Tweaks flow straight into the MushiProvider config prop.
    expect(out).toContain("position: 'top-left'")
    expect(out).toContain("theme: 'dark'")
  })
})

describe('renderSnippet — Vanilla', () => {
  it('uses a single Mushi.init() call carrying the entire config', () => {
    const out = renderSnippet('vanilla', PROJECT, KEY, tweakedConfig)
    expect(out).toContain("import { Mushi } from '@mushi-mushi/web'")
    expect(out).toMatch(/Mushi\.init\(\{/)
    expect(out).toContain("position: 'top-left'")
    expect(out).toContain('console: false')
  })
})
