export default {
  index: 'Overview',
  'open-source': 'Open source & licensing',
  credentials: 'Project ID & API keys',
  architecture: 'Architecture',
  'trigger-modes': 'Trigger modes',
  classification: 'Classification pipeline',
  'knowledge-graph': 'Knowledge graph',
  'fix-orchestrator': 'Agentic fix orchestrator',
  'multi-repo-fixes': 'Multi-repo coordinated fixes',
  'judge-loop': 'Judge & self-improvement',
  'anti-gaming': 'Anti-gaming & reputation',
  rewards: 'Rewards & contributor identity',
  'inventory-and-gates': 'Inventory & gates',
  'orchestrator-interop': 'Connecting your orchestrator',
  'closed-loop': 'Closed-loop evolution — the thesis',
  'evolution-loop': 'The evolution loop — five stages',
  'agent-contract': 'Agent contract',
  'bounty-marketplace': 'Bounty marketplace',
}
