export default {
  index: 'Overview',
  building: 'Building a plugin',
  events: 'Webhook events',
  'cursor-cloud': 'Cursor Cloud Agent',
  pagerduty: 'PagerDuty',
  linear: 'Linear',
  jira: 'Jira Cloud',
  slack: 'Slack app',
  discord: 'Discord',
  msteams: 'Microsoft Teams',
  'github-issues': 'GitHub Issues',
  sentry: 'Sentry',
  bugsnag: 'Bugsnag',
  rollbar: 'Rollbar',
  crashlytics: 'Crashlytics',
  zapier: 'Zapier',
}
