export default {
  index: 'Overview',
  core: '@mushi-mushi/core',
  web: '@mushi-mushi/web',
  presets: 'SDK presets',
  'nextjs-app-router-csp': 'Next.js App Router + CSP',
  'nextjs-static-export': 'Next.js static export',
  'capacitor-bottom-dock': 'Capacitor bottom dock',
  'sentry-replay-coexistence': 'Sentry Replay coexistence',
  react: '@mushi-mushi/react',
  vue: '@mushi-mushi/vue',
  svelte: '@mushi-mushi/svelte',
  angular: '@mushi-mushi/angular',
  'react-native': '@mushi-mushi/react-native',
  ios: 'MushiMushi (iOS)',
  android: 'dev.mushimushi:sdk (Android)',
  flutter: 'mushi_mushi (Flutter)',
  capacitor: '@mushi-mushi/capacitor',
  'wasm-classifier': '@mushi-mushi/wasm-classifier',
  cli: '@mushi-mushi/cli',
  mcp: '@mushi-mushi/mcp',
  'plugin-sdk': '@mushi-mushi/plugin-sdk',
}
