import { Card, Badge, Btn, RelativeTime } from '../ui'
import type { PromptVersion } from './types'
import { STAGE_LABELS } from './types'

/**
 * Domain-local tone ramp for judge scores (0.80 ok / 0.60 warn / <0.60 danger).
 * Mirrors JudgePage's ScorePill so an 0.80 eval is green in both views. We
 * intentionally don't delegate to ui.tsx#Pct / tokens.ts#pctToneClass here —
 * those use a 90/70 ramp tuned for health success rates / uptime, which
 * recolours legitimate 0.80–0.89 judge scores from green to amber. See the
 * comment in JudgePage#ScorePill for the full rationale.
 */
function judgeScoreTone(score: number): string {
  if (score >= 0.8) return 'text-ok'
  if (score >= 0.6) return 'text-warn'
  return 'text-danger'
}

interface PromptStageTableProps {
  stage: 'stage1' | 'stage2'
  prompts: PromptVersion[]
  busy: string | null
  onClone: (p: PromptVersion) => void
  onEdit: (p: PromptVersion) => void
  onDiff: (p: PromptVersion) => void
  onActivate: (p: PromptVersion) => void
  onTraffic: (p: PromptVersion) => void
  onDelete: (p: PromptVersion) => void
}

export function PromptStageTable({
  stage,
  prompts,
  busy,
  onClone,
  onEdit,
  onDiff,
  onActivate,
  onTraffic,
  onDelete,
}: PromptStageTableProps) {
  return (
    <Card elevated className="p-3">
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-xs font-semibold text-fg-secondary">
          {STAGE_LABELS[stage]}
        </h3>
        <span className="text-2xs text-fg-faint font-mono">
          {prompts.length} versions
        </span>
      </div>
      {prompts.length === 0 ? (
        <p className="text-2xs text-fg-faint">No prompts registered for this stage.</p>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-2xs">
            <thead className="text-fg-faint">
              <tr>
                <th className="text-left font-normal px-2 py-1">Version</th>
                <th className="text-left font-normal px-2 py-1">State</th>
                <th className="text-right font-normal px-2 py-1">Traffic</th>
                <th className="text-right font-normal px-2 py-1">Judge score</th>
                <th className="text-right font-normal px-2 py-1">Evals</th>
                <th className="text-left font-normal px-2 py-1">Updated</th>
                <th className="text-right font-normal px-2 py-1">Actions</th>
              </tr>
            </thead>
            <tbody>
              {prompts.map((p) => {
                const isGlobal = p.project_id == null
                const score = p.avg_judge_score
                return (
                  <tr key={p.id} className="border-t border-edge-subtle">
                    <td className="px-2 py-1.5 font-mono text-fg-secondary truncate max-w-[10rem]">
                      {p.version}
                    </td>
                    <td className="px-2 py-1.5">
                      {p.is_active ? (
                        <Badge className="bg-ok/15 text-ok border border-ok/30">Active</Badge>
                      ) : p.is_candidate ? (
                        <Badge className="bg-info/15 text-info border border-info/30">Candidate</Badge>
                      ) : (
                        <Badge className="bg-fg-faint/15 text-fg-muted border border-edge-subtle">Idle</Badge>
                      )}
                      {isGlobal && (
                        <Badge className="ml-1 bg-warn/15 text-warn border border-warn/30">Global</Badge>
                      )}
                      {p.auto_generated && (
                        <Badge
                          className="ml-1 bg-brand/15 text-brand border border-brand/30"
                          title={p.auto_generation_metadata?.changeSummary ?? 'Generated by prompt-auto-tune'}
                        >
                          Auto
                        </Badge>
                      )}
                    </td>
                    <td
                      className="px-2 py-1.5 text-right font-mono tabular-nums text-fg-faint"
                      title={p.traffic_percentage === 100
                        ? 'This version receives 100 % of live traffic for its stage.'
                        : `Receives ${p.traffic_percentage} % of live traffic; the remainder routes to other candidates in the same stage.`}
                    >
                      {/* Traffic is a deliberate A/B split, not a quality
                          signal. Rendering it through the higher-better tone
                          ramp would paint 50/50 experiments and 0 % idle
                          candidates red ("something's broken!") when they're
                          working exactly as configured. Keep this neutral
                          and match the JudgePage leaderboard treatment. */}
                      {p.traffic_percentage}%
                    </td>
                    <td className="px-2 py-1.5 text-right">
                      {score == null ? (
                        <span className="text-fg-faint text-2xs font-mono">—</span>
                      ) : (
                        <span
                          className={`font-mono tabular-nums ${judgeScoreTone(score)}`}
                          title="Judge score — higher is better. Uses the rolling 7-day eval window."
                        >
                          {(score * 100).toFixed(1)}%
                        </span>
                      )}
                    </td>
                    <td className="px-2 py-1.5 text-right font-mono text-fg-muted tabular-nums">
                      {p.total_evaluations}
                    </td>
                    <td className="px-2 py-1.5 text-fg-muted">
                      <RelativeTime value={p.updated_at} />
                    </td>
                    <td className="px-2 py-1.5 text-right space-x-1 whitespace-nowrap">
                      <Btn
                        size="sm"
                        variant="ghost"
                        disabled={busy === p.id}
                        onClick={() => onClone(p)}
                        title="Create an editable copy"
                      >
                        Clone
                      </Btn>
                      {!isGlobal && (
                        <>
                          <Btn size="sm" variant="ghost" disabled={busy === p.id} onClick={() => onEdit(p)}>
                            Edit
                          </Btn>
                          {p.parent_version_id && (
                            <Btn
                              size="sm"
                              variant="ghost"
                              disabled={busy === p.id}
                              onClick={() => onDiff(p)}
                              title="Diff against parent prompt"
                            >
                              Diff
                            </Btn>
                          )}
                          {!p.is_active && (
                            <Btn
                              size="sm"
                              variant="ghost"
                              disabled={busy === p.id}
                              onClick={() => onActivate(p)}
                              title="Make this the live prompt for this stage"
                            >
                              Activate
                            </Btn>
                          )}
                          {!p.is_active && (
                            <Btn
                              size="sm"
                              variant="ghost"
                              disabled={busy === p.id}
                              onClick={() => onTraffic(p)}
                            >
                              Traffic
                            </Btn>
                          )}
                          <Btn
                            size="sm"
                            variant="danger"
                            disabled={busy === p.id || p.is_active}
                            onClick={() => onDelete(p)}
                          >
                            Delete
                          </Btn>
                        </>
                      )}
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>
      )}
    </Card>
  )
}
